# Generated by Django 2.0.7 on 2018-07-18 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_item_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='aeoo_int',
            field=models.PositiveIntegerField(blank=True, help_text='If item is an AEOO item, this is the number of days it will expire after being opened', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='current_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='pack_int',
            field=models.PositiveIntegerField(blank=True, help_text='If item is pack item, this is the number of required QR codes for this item', null=True),
        ),
    ]
